# Generated by Django 4.2.7 on 2025-09-08 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagrams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_sessions', to='diagrams.diagram')),
            ],
        ),
        migrations.CreateModel(
            name='UserCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursors', to='collaboration.collaborationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('cursor_position', models.JSONField(default=dict)),
                ('selected_elements', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('user_color', models.CharField(default='#007bff', max_length=7)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='collaboration.collaborationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'is_active', 'last_seen'], name='collaborati_session_1e91e6_idx')],
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ElementLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('lock_type', models.CharField(default='edit', max_length=20)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='diagrams.diagramelement')),
                ('locked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_locks', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_locks', to='collaboration.collaborationsession')),
            ],
            options={
                'indexes': [models.Index(fields=['locked_by', 'expires_at'], name='collaborati_locked__fd03b5_idx'), models.Index(fields=['element', 'expires_at'], name='collaborati_element_d83cd0_idx')],
                'unique_together': {('element', 'session')},
            },
        ),
        migrations.CreateModel(
            name='DiagramChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('element_created', 'Element Created'), ('element_updated', 'Element Updated'), ('element_deleted', 'Element Deleted'), ('element_moved', 'Element Moved'), ('attribute_created', 'Attribute Created'), ('attribute_updated', 'Attribute Updated'), ('attribute_deleted', 'Attribute Deleted'), ('method_created', 'Method Created'), ('method_updated', 'Method Updated'), ('method_deleted', 'Method Deleted'), ('relationship_created', 'Relationship Created'), ('relationship_updated', 'Relationship Updated'), ('relationship_deleted', 'Relationship Deleted'), ('canvas_updated', 'Canvas Updated')], max_length=30)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('change_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sequence_number', models.BigIntegerField()),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='diagrams.diagram')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='collaboration.collaborationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagram_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence_number'],
                'indexes': [models.Index(fields=['diagram', 'timestamp'], name='collaborati_diagram_b94dfd_idx'), models.Index(fields=['session', 'sequence_number'], name='collaborati_session_eb1975_idx'), models.Index(fields=['user', 'timestamp'], name='collaborati_user_id_bfccd2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='diagrams.diagram')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='diagrams.diagramelement')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['diagram', 'is_resolved', '-created_at'], name='collaborati_diagram_6bba95_idx'), models.Index(fields=['element', '-created_at'], name='collaborati_element_305bd2_idx')],
            },
        ),
    ]
