# Generated by Django 4.2.7 on 2025-09-09 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=255)),
                ('diagram_id', models.UUIDField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagram_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['diagram_id', 'user'], name='collaborati_diagram_1b79a8_idx'), models.Index(fields=['element_id', 'diagram_id'], name='collaborati_element_c00712_idx'), models.Index(fields=['user', 'locked_at'], name='collaborati_user_id_9990c3_idx')],
                'unique_together': {('element_id', 'diagram_id')},
            },
        ),
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_id', models.UUIDField()),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_diagram_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['diagram_id', 'last_seen'], name='collaborati_diagram_d53101_idx'), models.Index(fields=['user', 'diagram_id'], name='collaborati_user_id_ef44cd_idx')],
                'unique_together': {('user', 'diagram_id')},
            },
        ),
    ]
