# Generated by Django 4.2.7 on 2025-09-09 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('diagrams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaboration', '0002_diagramlock_activeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('project_invite', 'Project Invitation'), ('project_update', 'Project Updated'), ('diagram_shared', 'Diagram Shared'), ('comment_added', 'Comment Added'), ('mention', 'User Mentioned'), ('collaboration_request', 'Collaboration Request'), ('element_conflict', 'Element Conflict'), ('project_role_changed', 'Project Role Changed')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('diagram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagrams.diagram')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='collaborati_recipie_9095d3_idx'), models.Index(fields=['recipient', 'notification_type', '-created_at'], name='collaborati_recipie_778f65_idx'), models.Index(fields=['project', '-created_at'], name='collaborati_project_5be667_idx'), models.Index(fields=['diagram', '-created_at'], name='collaborati_diagram_b0d3b2_idx')],
            },
        ),
    ]
