# Generated by Django 4.2.7 on 2025-09-08 15:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, null=True)),
                ('diagram_type', models.CharField(choices=[('class', 'Class Diagram'), ('database', 'Database Diagram'), ('er', 'Entity Relationship Diagram')], default='class', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canvas_data', models.JSONField(default=dict)),
                ('version', models.IntegerField(default=1)),
                ('is_template', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_diagrams', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_diagrams', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagramElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('element_type', models.CharField(choices=[('class', 'Class'), ('interface', 'Interface'), ('abstract_class', 'Abstract Class'), ('enum', 'Enumeration'), ('table', 'Database Table'), ('view', 'Database View'), ('package', 'Package'), ('note', 'Note')], max_length=20)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('width', models.FloatField(default=200)),
                ('height', models.FloatField(default=150)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
                ('visibility', models.CharField(default='public', max_length=20)),
                ('stereotype', models.CharField(blank=True, max_length=50, null=True)),
                ('documentation', models.TextField(blank=True, null=True)),
                ('properties', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='diagrams.diagram')),
            ],
        ),
        migrations.CreateModel(
            name='ElementMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('return_type', models.CharField(default='void', max_length=50)),
                ('visibility', models.CharField(choices=[('+', 'Public'), ('-', 'Private'), ('#', 'Protected'), ('~', 'Package')], default='+', max_length=1)),
                ('is_static', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('is_abstract', models.BooleanField(default=False)),
                ('is_constructor', models.BooleanField(default=False)),
                ('parameters', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('documentation', models.TextField(blank=True, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='diagrams.diagramelement')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ElementAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('int', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('list', 'List'), ('dict', 'Dictionary'), ('object', 'Object'), ('varchar', 'VARCHAR'), ('text', 'TEXT'), ('integer', 'INTEGER'), ('bigint', 'BIGINT'), ('decimal', 'DECIMAL'), ('float', 'FLOAT'), ('double', 'DOUBLE'), ('boolean', 'BOOLEAN'), ('date', 'DATE'), ('timestamp', 'TIMESTAMP'), ('json', 'JSON'), ('uuid', 'UUID')], default='string', max_length=50)),
                ('visibility', models.CharField(choices=[('+', 'Public'), ('-', 'Private'), ('#', 'Protected'), ('~', 'Package')], default='+', max_length=1)),
                ('is_static', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('is_abstract', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=200, null=True)),
                ('constraints', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
                ('documentation', models.TextField(blank=True, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='diagrams.diagramelement')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('element', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DiagramVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changes_summary', models.TextField(blank=True, null=True)),
                ('snapshot_data', models.JSONField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='diagrams.diagram')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('diagram', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='DiagramRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('inheritance', 'Inheritance (is-a)'), ('realization', 'Realization (implements)'), ('composition', 'Composition (strong has-a)'), ('aggregation', 'Aggregation (weak has-a)'), ('association', 'Association'), ('dependency', 'Dependency (uses)'), ('one_to_one', 'One to One'), ('one_to_many', 'One to Many'), ('many_to_many', 'Many to Many'), ('foreign_key', 'Foreign Key')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('source_multiplicity', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('0..1', '0..1'), ('1..1', '1..1'), ('0..*', '0..*'), ('1..*', '1..*'), ('*', '*'), ('n', 'n')], max_length=10, null=True)),
                ('target_multiplicity', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('0..1', '0..1'), ('1..1', '1..1'), ('0..*', '0..*'), ('1..*', '1..*'), ('*', '*'), ('n', 'n')], max_length=10, null=True)),
                ('source_role', models.CharField(blank=True, max_length=50, null=True)),
                ('target_role', models.CharField(blank=True, max_length=50, null=True)),
                ('is_navigable', models.BooleanField(default=True)),
                ('line_style', models.CharField(default='solid', max_length=20)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('waypoints', models.JSONField(default=list)),
                ('properties', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='diagrams.diagram')),
                ('source_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='diagrams.diagramelement')),
                ('target_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='diagrams.diagramelement')),
            ],
            options={
                'indexes': [models.Index(fields=['diagram', 'relationship_type'], name='diagrams_di_diagram_8f2246_idx'), models.Index(fields=['source_element'], name='diagrams_di_source__ca1e52_idx'), models.Index(fields=['target_element'], name='diagrams_di_target__32b293_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='diagramelement',
            index=models.Index(fields=['diagram', 'element_type'], name='diagrams_di_diagram_60953d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diagramelement',
            unique_together={('diagram', 'name')},
        ),
        migrations.AddIndex(
            model_name='diagram',
            index=models.Index(fields=['project', '-updated_at'], name='diagrams_di_project_d52d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='diagram',
            index=models.Index(fields=['diagram_type', '-updated_at'], name='diagrams_di_diagram_233fc9_idx'),
        ),
    ]
