# Generated by Django 4.2.7 on 2025-09-08 15:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagrams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('output_format', models.CharField(choices=[('zip', 'ZIP Archive'), ('tar', 'TAR Archive'), ('folder', 'Folder Structure')], default='zip', max_length=10)),
                ('configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='generated_code/')),
                ('output_size', models.BigIntegerField(blank=True, null=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='diagrams.diagram')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite'), ('oracle', 'Oracle'), ('sqlserver', 'SQL Server'), ('mongodb', 'MongoDB')], max_length=20)),
                ('schema_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ddl_script', models.TextField()),
                ('migration_scripts', models.JSONField(default=list)),
                ('indexes', models.JSONField(default=list)),
                ('constraints', models.JSONField(default=list)),
                ('generation_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_schemas', to='code_generation.codegenerationjob')),
            ],
        ),
        migrations.CreateModel(
            name='CodeGenerationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, null=True)),
                ('template_type', models.CharField(choices=[('spring_boot', 'Spring Boot'), ('django', 'Django'), ('nodejs', 'Node.js'), ('dotnet', '.NET Core'), ('laravel', 'Laravel'), ('database', 'Database Schema')], max_length=20)),
                ('language', models.CharField(choices=[('java', 'Java'), ('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('csharp', 'C#'), ('php', 'PHP'), ('sql', 'SQL')], max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('template_content', models.JSONField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='codegenerationjob',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='code_generation.codegenerationtemplate'),
        ),
        migrations.CreateModel(
            name='CodeGenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_version', models.IntegerField()),
                ('generated_at', models.DateTimeField()),
                ('files_count', models.IntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_history', to='diagrams.diagram')),
                ('generation_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='code_generation.codegenerationjob')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('entity', 'Entity/Model'), ('repository', 'Repository'), ('service', 'Service'), ('controller', 'Controller'), ('config', 'Configuration'), ('test', 'Test File'), ('migration', 'Database Migration'), ('schema', 'Database Schema'), ('documentation', 'Documentation'), ('other', 'Other')], default='other', max_length=20)),
                ('content', models.TextField()),
                ('size', models.IntegerField()),
                ('based_on_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_files', to='diagrams.diagramelement')),
                ('generation_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_files', to='code_generation.codegenerationjob')),
            ],
            options={
                'ordering': ['file_path', 'file_name'],
                'indexes': [models.Index(fields=['generation_job', 'file_type'], name='code_genera_generat_78b22e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='codegenerationtemplate',
            index=models.Index(fields=['template_type', 'language'], name='code_genera_templat_51875a_idx'),
        ),
        migrations.AddIndex(
            model_name='codegenerationtemplate',
            index=models.Index(fields=['is_default', 'is_active'], name='code_genera_is_defa_22190f_idx'),
        ),
        migrations.AddIndex(
            model_name='codegenerationjob',
            index=models.Index(fields=['requested_by', '-created_at'], name='code_genera_request_15fc66_idx'),
        ),
        migrations.AddIndex(
            model_name='codegenerationjob',
            index=models.Index(fields=['status', '-created_at'], name='code_genera_status_427a34_idx'),
        ),
        migrations.AddIndex(
            model_name='codegenerationjob',
            index=models.Index(fields=['diagram', '-created_at'], name='code_genera_diagram_c0c554_idx'),
        ),
    ]
